name: CI - Desbravadores Gestao API

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Locate solution
        id: solution
        shell: bash
        run: |
          SLN=$(find . -maxdepth 3 -name "*.sln" | head -n 1)

          if [ -z "$SLN" ]; then
            echo "Nenhum arquivo .sln encontrado."
            exit 1
          fi

          echo "Solution encontrada: $SLN"
          echo "path=$SLN" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore "${{ steps.solution.outputs.path }}"

      - name: Build
        run: dotnet build "${{ steps.solution.outputs.path }}" --no-restore --configuration Release

      - name: Run tests
        run: dotnet test "${{ steps.solution.outputs.path }}" --no-build --configuration Release --verbosity normal

      - name: Publish
        run: dotnet publish ./src/Desbravadores.Gestao.Api/Desbravadores.Gestao.Api.csproj --no-build --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: desbravadores-api
          path: ./publish